import { StateProvider } from "./StateProvider.js"
import reducer, {initialState} from "./reducer.js"


export const metadata = {
  title: 'My Amazon',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateProvider initialState={initialState} reducer={reducer}>
        <body>{children}</body>
      </StateProvider>
    </html>
  )
}
