import { StateProvider } from "./StateProvider.js"
import reducer, { getInitialState } from "./reducer.js"



export const metadata = {
  title: 'My Amazon',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateProvider initialState={getInitialState} reducer={reducer}>
        <body>{children}</body>
      </StateProvider>
    </html>
  )
}
