import { StateProvider } from "./StateProvider.js"
import reducer, {initialState} from "./reducer.js"
import CheckUser from "./CheckUser.js";


export const metadata = {
  title: 'My Amazon',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateProvider initialState={initialState} reducer={reducer}>
          <CheckUser />
          {children}
        </StateProvider>
      </body>
    </html>
  )
}
